### ISSUE TITLE
Bundle 'org.eclipse.xtext.generator' cannot be resolved

### ISSUE THREAD

**Issue by iperdomo** [integratedmodelling/klab#22]
## Context

When we upgraded to use Eclipse 2022-06 (Issue #18), we also upgraded the version of Xtext to 2.27.0

> Changes to `org.eclipse.xtext.sdk` feature.
> The `org.eclipse.xtext.sdk` does no longer package the deprecated `org.eclipse.xtext.generator` bundle. Please migrate to the new workflow/generator. The old and deprecated generator can still be found in the new `org.eclipse.xtext.generator` feature.

Source: https://www.eclipse.org/Xtext/releasenotes.html#/releasenotes/2022/05/30/version-2-27-0

After an Eclipse import of the projects, the validator reports the missing `org.eclipse.xtext.generator` bundle, referenced in 
https://github.com/integratedmodelling/klab/blob/1c45c5cb55e73330883dc729a9c8a9fa02ad400b/kim/org.integratedmodelling.kim/META-INF/MANIFEST.MF#L18

![2023-02-15_1183x628](https://user-images.githubusercontent.com/178474/219145820-68208424-465c-4f15-b336-ef7dd24f4d1b.png)

More references to the `org.eclipse.xtext.generator` package are located at:
https://github.com/integratedmodelling/klab/blob/1c45c5cb55e73330883dc729a9c8a9fa02ad400b/kim/org.integratedmodelling.kim.target/org.integratedmodelling.kim.target.target#L21
https://github.com/integratedmodelling/klab/blob/1c45c5cb55e73330883dc729a9c8a9fa02ad400b/kim/org.integratedmodelling.kim/src/org/integratedmodelling/kim/GenerateKim.mwe2#L3-L4
https://github.com/integratedmodelling/klab/blob/1c45c5cb55e73330883dc729a9c8a9fa02ad400b/kim/org.integratedmodelling.kim/src/org/integratedmodelling/kim/generator/KimGenerator.xtend#L7-L9
This last references are to a class that seems to be doing _nothing_.

Since we suggest the _current active_ platform as target platform (for Plug-in Development), it means [Eclipse IDE for Java and DSL Developers - 2022-06](https://www.eclipse.org/downloads/packages/release/2022-06/r/eclipse-ide-java-and-dsl-developers) that only includes the `org.eclipse.xtext.sdk` feature, and not `org.eclipse.xtext.generator` feature.

## Next steps

We have a couple of options

- A developer can easily ignore this problem by choosing a _Warning_ level for "Unresolved dependencies" under Plug-in Development
- We can mark the dependency as `optional` in `MANIFEST.MF`
- We can remove the reference to `org.eclipse.xtext.generator` bundle in `MANIFEST.MF`

The last option would be the preferred one, as is a deprecated bundle, but I'm not completely sure what are the implications of that change.

**Comment by iperdomo** [comment]
@fvilla your input (and context) on this issue is more than welcome

**Comment by iperdomo** [comment]
Doing an `mvn clean install -DskipTests` (the build process followed by [CI](https://github.com/integratedmodelling/klab/blob/1c45c5cb55e73330883dc729a9c8a9fa02ad400b/Jenkinsfile#L162)) works, with the following changes.

```diff
diff --git a/kim/org.integratedmodelling.kim.target/org.integratedmodelling.kim.target.target b/kim/org.integratedmodelling.kim.target/org.integratedmodelling.kim.target.target
index 006b41740..b3d112e8a 100644
--- a/kim/org.integratedmodelling.kim.target/org.integratedmodelling.kim.target.target
+++ b/kim/org.integratedmodelling.kim.target/org.integratedmodelling.kim.target.target
@@ -18,7 +18,6 @@
 </location>
 <location includeAllPlatforms="false" includeConfigurePhase="false" includeMode="planner" includeSource="false" type="InstallableUnit">
   <unit id="org.eclipse.xtext.sdk.feature.group" version="0.0.0"/>
-  <unit id="org.eclipse.xtext.generator.feature.group" version="0.0.0"/>
 <repository location="https://download.eclipse.org/modeling/tmf/xtext/updates/releases/2.27.0/"/>
 </location>
 </locations>
diff --git a/kim/org.integratedmodelling.kim/META-INF/MANIFEST.MF b/kim/org.integratedmodelling.kim/META-INF/MANIFEST.MF
index a3b5fbabf..0c566e265 100644
--- a/kim/org.integratedmodelling.kim/META-INF/MANIFEST.MF
+++ b/kim/org.integratedmodelling.kim/META-INF/MANIFEST.MF
@@ -15,7 +15,6 @@ Require-Bundle: org.eclipse.xtext,
  org.eclipse.xtend.lib;bundle-version="2.14.0",
  org.eclipse.emf.common,
  com.ibm.icu,
- org.eclipse.xtext.generator,
  org.integratedmodelling.klab.api;bundle-version="0.11.0",
  org.integratedmodelling.kactors;bundle-version="0.11.0"
 Bundle-RequiredExecutionEnvironment: JavaSE-11

```

**Comment by fvilla** [comment]
I'd be in favor of removing the dependency. This means we all need to switch to 2022-06 but that doesn't sound like a big problem.

**Comment by iperdomo** [comment]
Related #19
