### ISSUE TITLE
Upgrade maven-war-plugin to latest version

### ISSUE THREAD

**Issue by iperdomo** [integratedmodelling/klab#9]
## Context
Eclipse IDE complains with misleading error due to an outdated maven-war-plugin version.

```
Could not initialize class org.apache.maven.plugin.war.util.WebappStructureSerializer
```
![2022-06-10_1424x70](https://user-images.githubusercontent.com/178474/173022721-6271fdc2-b974-4812-9e5c-432a7ec51f34.png)

## Environment
* OS: Arch Linux 5.18.2-arch1-1
* Java: openjdk version "11.0.15" 2022-04-19
* Eclipse: Eclipse IDE for Enterprise Java and Web Developers - Version: 2022-03 (4.23.0) - Build id: 20220310-1457

## Solution

Upgrading to latest (3.3.2) [maven-war-plugin](https://search.maven.org/artifact/org.apache.maven.plugins/maven-war-plugin/3.3.2/maven-plugin) solves the problem

**Comment by fvilla** [comment]
+1 - these are originally created by xText and they have no upgrade mechanism for existing projects AFAIK
